# Generated by Django 6.0.4 on 2026-05-06 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_materialpurchase_materialpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='materialpurchase',
            old_name='amoount',
            new_name='amount',
        ),
    ]
